// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

//! Utils to make testing easier

use bastion_utils::math::random;
use std::{env, fs, io::Write};

/// Returns a vector of size `n`, filled with randomly generated bytes.
pub fn random_bytes(n: usize) -> Vec<u8> {
    let mut result = vec![];
    for _ in 0..n {
        result.push(random(255) as _);
    }
    result
}

/// Returns a random bool with given falsification ratio `r`.
pub fn random_bool(r: f32) -> bool {
    if random(100) > (r * 100_f32) as u32 {
        true
    } else {
        false
    }
}

/// Returns random bools in a vector of size `n` with given falsification ratio `r`.
pub fn random_bools(n: usize, r: f32) -> Vec<bool> {
    (0..n).into_iter().map(|_| random_bool(r)).collect()
}

/// Returns random string with length of `n`.
pub fn random_string(n: usize) -> String {
    let bytes = random_bytes(n * 100);
    String::from_utf8_lossy(&*bytes).to_string()
}

/// Returns random value in range starting at `start` and ending at `end`.
pub fn random_in_range(start: usize, end: usize) -> usize {
    let v = random(end as _) as usize;
    if start < v {
        v
    } else {
        random_in_range(start, end)
    }
}

/// Returns a random 32-bit float
pub fn random_float() -> f32 {
    let v = random_in_range(100_000_000, 300_000_000);
    (v / 100_000_000) as f32
}

/// Returns file handle for a temp file in 'target' directory with a provided content
///
/// TODO: Originates from `parquet` utils, can be merged in [ARROW-4064]
pub fn get_temp_file(file_name: &str, content: &[u8]) -> fs::File {
    // build tmp path to a file in "target/debug/testdata"
    let mut path_buf = env::current_dir().unwrap();
    path_buf.push("target");
    path_buf.push("debug");
    path_buf.push("testdata");
    fs::create_dir_all(&path_buf).unwrap();
    path_buf.push(file_name);

    // write file content
    let mut tmp_file = fs::File::create(path_buf.as_path()).unwrap();
    tmp_file.write_all(content).unwrap();
    tmp_file.sync_all().unwrap();

    // return file handle for both read and write
    let file = fs::OpenOptions::new()
        .read(true)
        .write(true)
        .open(path_buf.as_path());
    assert!(file.is_ok());
    file.unwrap()
}
